#include "StdAfx.h"
#include "ControlFactory.h"

namespace DuiLib 
{
	CControlFactory::CControlFactory()
	{
		INNER_REGISTER_DUICONTROL(CControlUI);
		INNER_REGISTER_DUICONTROL(CContainerUI);
		INNER_REGISTER_DUICONTROL(CButtonUI);
		INNER_REGISTER_DUICONTROL(CComboUI);
		INNER_REGISTER_DUICONTROL(CComboBoxUI);
		INNER_REGISTER_DUICONTROL(CDateTimeUI);
		INNER_REGISTER_DUICONTROL(CStepsUI);
		INNER_REGISTER_DUICONTROL(CStepItemUI);
		INNER_REGISTER_DUICONTROL(CTimelineUI);
		INNER_REGISTER_DUICONTROL(CTimelineItemUI);
		INNER_REGISTER_DUICONTROL(CEditUI);
		INNER_REGISTER_DUICONTROL(CSpinUI);
		INNER_REGISTER_DUICONTROL(CSegmentedUI);
		INNER_REGISTER_DUICONTROL(CSegmentItemUI);
		INNER_REGISTER_DUICONTROL(CTagUI);
		INNER_REGISTER_DUICONTROL(CBadgeUI);
		INNER_REGISTER_DUICONTROL(CTransferUI);
		INNER_REGISTER_DUICONTROL(CTransferItemUI);
		INNER_REGISTER_DUICONTROL(CRateUI);
		INNER_REGISTER_DUICONTROL(CEmptyUI);
		INNER_REGISTER_DUICONTROL(CSkeletonUI);
		INNER_REGISTER_DUICONTROL(CActiveXUI);
		INNER_REGISTER_DUICONTROL(CFlashUI);
		INNER_REGISTER_DUICONTROL(CGifAnimUI);
#ifdef USE_XIMAGE_EFFECT
		INNER_REGISTER_DUICONTROL(CGifAnimExUI);
#endif
		INNER_REGISTER_DUICONTROL(CGroupBoxUI);
		INNER_REGISTER_DUICONTROL(CIPAddressUI);
		INNER_REGISTER_DUICONTROL(CIPAddressExUI);
		INNER_REGISTER_DUICONTROL(CLabelUI);
		INNER_REGISTER_DUICONTROL(CListUI);
		INNER_REGISTER_DUICONTROL(CVirtualListUI);
		INNER_REGISTER_DUICONTROL(CListHeaderUI);
		INNER_REGISTER_DUICONTROL(CListHeaderItemUI);
		INNER_REGISTER_DUICONTROL(CListLabelElementUI);
		INNER_REGISTER_DUICONTROL(CListTextElementUI);
		INNER_REGISTER_DUICONTROL(CListContainerElementUI);
		INNER_REGISTER_DUICONTROL(CMenuUI);
		INNER_REGISTER_DUICONTROL(CMenuElementUI);
		INNER_REGISTER_DUICONTROL(COptionUI);
		INNER_REGISTER_DUICONTROL(CCheckBoxUI);
		INNER_REGISTER_DUICONTROL(CSwitchUI);
		INNER_REGISTER_DUICONTROL(CImageUI);
		INNER_REGISTER_DUICONTROL(CAvatarUI);
		INNER_REGISTER_DUICONTROL(CFontIconUI);
		INNER_REGISTER_DUICONTROL(CProgressUI);
		INNER_REGISTER_DUICONTROL(CRichEditUI);
		INNER_REGISTER_DUICONTROL(CScrollBarUI);
		INNER_REGISTER_DUICONTROL(CSliderUI);
		INNER_REGISTER_DUICONTROL(CTextUI);
		INNER_REGISTER_DUICONTROL(CTreeNodeUI);
		INNER_REGISTER_DUICONTROL(CTreeViewUI);
		INNER_REGISTER_DUICONTROL(CWebBrowserUI);
		INNER_REGISTER_DUICONTROL(CWebView2UI);
		INNER_REGISTER_DUICONTROL(CAnimationTabLayoutUI);
		INNER_REGISTER_DUICONTROL(CChildLayoutUI);
		INNER_REGISTER_DUICONTROL(CHorizontalLayoutUI);
		INNER_REGISTER_DUICONTROL(CTabLayoutUI);
		INNER_REGISTER_DUICONTROL(CTileLayoutUI);
		INNER_REGISTER_DUICONTROL(CVerticalLayoutUI);
		INNER_REGISTER_DUICONTROL(CRollTextUI);
		INNER_REGISTER_DUICONTROL(CColorPaletteUI);
		INNER_REGISTER_DUICONTROL(CThemeSwitcherUI);
		INNER_REGISTER_DUICONTROL(CListExUI);
		INNER_REGISTER_DUICONTROL(CListContainerHeaderItemUI);
		INNER_REGISTER_DUICONTROL(CListTextExtElementUI);
		INNER_REGISTER_DUICONTROL(CHotKeyUI);
		INNER_REGISTER_DUICONTROL(CFadeButtonUI);
		INNER_REGISTER_DUICONTROL(CRingUI);
		INNER_REGISTER_DUICONTROL(CLoadingUI);
		INNER_REGISTER_DUICONTROL(CPageControlUI);
		INNER_REGISTER_DUICONTROL(CSpacerUI);
		INNER_REGISTER_DUICONTROL(CAccordionUI);
		INNER_REGISTER_DUICONTROL(CAccordionItemUI);
		INNER_REGISTER_DUICONTROL(CCarouselUI);
		INNER_REGISTER_DUICONTROL(CCarouselItemUI);
		INNER_REGISTER_DUICONTROL(CSidePanelUI);
		INNER_REGISTER_DUICONTROL(CSvgBoxUI);
		INNER_REGISTER_DUICONTROL(CTabBarUI);
		INNER_REGISTER_DUICONTROL(CTabButtonUI);
		INNER_REGISTER_DUICONTROL(CTitleBarUI);
		INNER_REGISTER_DUICONTROL(CTitleBarLeftUI);
		INNER_REGISTER_DUICONTROL(CTitleBarSysUI);
		INNER_REGISTER_DUICONTROL(CFlowLayoutUI);

        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_BOX, CContainerUI);
        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_HBOX, CHorizontalLayoutUI);
        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_VBOX, CVerticalLayoutUI);
        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_TAB_BOX, CTabLayoutUI);
        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_TILE_BOX, CTileLayoutUI);
        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_CHILD_BOX, CChildLayoutUI);
		// body：页面根容器，纵向堆叠（与 html>body 一致）；勿用 FlowLayout——
		// VBox/HBox 的 EstimateSize 高为 0 表示撑满，Flow 会当成 0 高导致只剩标题栏
        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_BODY, CVerticalLayoutUI);
        INNER_REGISTER_DUICONTROL_EX(DUI_CTR_DIV, CFlowLayoutUI);
		INNER_REGISTER_DUICONTROL_EX(_T("accordion"), CAccordionUI);
		INNER_REGISTER_DUICONTROL_EX(_T("accordion-item"), CAccordionItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("carousel"), CCarouselUI);
		INNER_REGISTER_DUICONTROL_EX(_T("carousel-item"), CCarouselItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("sidepanel"), CSidePanelUI);
		INNER_REGISTER_DUICONTROL_EX(_T("SidePanel"), CSidePanelUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Svg"), CSvgBoxUI);
		INNER_REGISTER_DUICONTROL_EX(_T("svg"), CSvgBoxUI);
		INNER_REGISTER_DUICONTROL_EX(_T("tabbar"), CTabBarUI);
		INNER_REGISTER_DUICONTROL_EX(_T("tabbutton"), CTabButtonUI);
		INNER_REGISTER_DUICONTROL_EX(_T("titlebar"), CTitleBarUI);
		INNER_REGISTER_DUICONTROL_EX(_T("TitleBar"), CTitleBarUI);
		INNER_REGISTER_DUICONTROL_EX(_T("switch"), CSwitchUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Switch"), CSwitchUI);
		INNER_REGISTER_DUICONTROL_EX(_T("virtuallist"), CVirtualListUI);
		INNER_REGISTER_DUICONTROL_EX(_T("VirtualList"), CVirtualListUI);
		// 勿用 <Image>：构建器里已是皮肤资源声明标签
		INNER_REGISTER_DUICONTROL_EX(_T("Img"), CImageUI);
		INNER_REGISTER_DUICONTROL_EX(_T("img"), CImageUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Picture"), CImageUI);
		INNER_REGISTER_DUICONTROL_EX(_T("ImageBox"), CImageUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Avatar"), CAvatarUI);
		INNER_REGISTER_DUICONTROL_EX(_T("avatar"), CAvatarUI);
		INNER_REGISTER_DUICONTROL_EX(_T("FontIcon"), CFontIconUI);
		INNER_REGISTER_DUICONTROL_EX(_T("fonticon"), CFontIconUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Steps"), CStepsUI);
		INNER_REGISTER_DUICONTROL_EX(_T("steps"), CStepsUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Step"), CStepItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("StepItem"), CStepItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Timeline"), CTimelineUI);
		INNER_REGISTER_DUICONTROL_EX(_T("timeline"), CTimelineUI);
		INNER_REGISTER_DUICONTROL_EX(_T("TimelineItem"), CTimelineItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("timeline-item"), CTimelineItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Spin"), CSpinUI);
		INNER_REGISTER_DUICONTROL_EX(_T("spin"), CSpinUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Number"), CSpinUI);
		INNER_REGISTER_DUICONTROL_EX(_T("number"), CSpinUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Segmented"), CSegmentedUI);
		INNER_REGISTER_DUICONTROL_EX(_T("segmented"), CSegmentedUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Segment"), CSegmentItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("segment"), CSegmentItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("SegmentItem"), CSegmentItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("ThemeSwitcher"), CThemeSwitcherUI);
		INNER_REGISTER_DUICONTROL_EX(_T("themeswitcher"), CThemeSwitcherUI);
		INNER_REGISTER_DUICONTROL_EX(_T("segment-item"), CSegmentItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Tag"), CTagUI);
		INNER_REGISTER_DUICONTROL_EX(_T("tag"), CTagUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Badge"), CBadgeUI);
		INNER_REGISTER_DUICONTROL_EX(_T("badge"), CBadgeUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Transfer"), CTransferUI);
		INNER_REGISTER_DUICONTROL_EX(_T("transfer"), CTransferUI);
		INNER_REGISTER_DUICONTROL_EX(_T("TransferItem"), CTransferItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("transfer-item"), CTransferItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("transferitem"), CTransferItemUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Rate"), CRateUI);
		INNER_REGISTER_DUICONTROL_EX(_T("rate"), CRateUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Empty"), CEmptyUI);
		INNER_REGISTER_DUICONTROL_EX(_T("empty"), CEmptyUI);
		INNER_REGISTER_DUICONTROL_EX(_T("Skeleton"), CSkeletonUI);
		INNER_REGISTER_DUICONTROL_EX(_T("skeleton"), CSkeletonUI);
	}

	CControlFactory::~CControlFactory()
	{
	}

	CControlUI* CControlFactory::CreateControl(CDuiString strClassName)
	{
		strClassName.MakeLower();
		MAP_DUI_CTRATECLASS::iterator iter = m_mapControl.find(strClassName);
		if ( iter == m_mapControl.end()) {
			return NULL;
		}
		else {
			return (CControlUI*) (iter->second());
		}
	}

	void CControlFactory::RegistControl(CDuiString strClassName, CreateClass pFunc)
	{
		strClassName.MakeLower();
		m_mapControl.insert(MAP_DUI_CTRATECLASS::value_type(strClassName, pFunc));
	}

	CControlFactory* CControlFactory::GetInstance()  
	{
		static CControlFactory* pInstance = new CControlFactory;
		return pInstance;
	}

	void CControlFactory::Release()
	{
		delete this;
	}
}